<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Question;

class QuestionsTableSeeder extends Seeder
{
    public function run()
    {
        $questions = [
            [
                'page' => 1,
                'question_key' => 'industry',
                'question' => 'What industry are you working in?',
                'answer_type' => 'single_select',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 1,
                'question_key' => 'country_live',
                'question' => 'Where do you live?',
                'answer_type' => 'single_select',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 1,
                'question_key' => 'country_born',
                'question' => 'Where were you born?',
                'answer_type' => 'single_select',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 1,
                'question_key' => 'church',
                'question' => 'What church do you go to?',
                'answer_type' => 'single_select',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 1,
                'question_key' => 'attend_church',
                'question' => 'Do you go to church every Sunday?',
                'answer_type' => 'boolean',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 1,
                'question_key' => 'married',
                'question' => 'Have you been married?',
                'answer_type' => 'boolean',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 1,
                'question_key' => 'kids',
                'question' => 'Do you have kids?',
                'answer_type' => 'boolean',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 1,
                'question_key' => 'father_name',
                'question' => 'What was your father\'s first and last name when he was born?',
                'answer_type' => 'text',
                'is_editable' => false,
                'is_required' => true,
            ],
            [
                'page' => 1,
                'question_key' => 'mother_name',
                'question' => 'What is your mother\'s first and last name?',
                'answer_type' => 'text',
                'is_editable' => false,
                'is_required' => true,
            ],
            [
                'page' => 1,
                'question_key' => 'education',
                'question' => 'What is your education level?',
                'answer_type' => 'single_select',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 1,
                'question_key' => 'siblings',
                'question' => 'How many siblings do you have?',
                'answer_type' => 'numeric',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 1,
                'question_key' => 'sports_play',
                'question' => 'Do you play any sports?',
                'answer_type' => 'boolean',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 1,
                'question_key' => 'sports_watch',
                'question' => 'Do you watch any sports?',
                'answer_type' => 'boolean',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 2,
                'question_key' => 'favorite_movie',
                'question' => 'What’s your favorite movie?',
                'answer_type' => 'multi_select',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 2,
                'question_key' => 'news_media',
                'question' => 'What media do you watch for news?',
                'answer_type' => 'multi_select',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 2,
                'question_key' => 'ideal_family_place',
                'question' => 'Where is your ideal place to live and raise a family?',
                'answer_type' => 'multi_select',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 2,
                'question_key' => 'vacation',
                'question' => 'Do you take a vacation?',
                'answer_type' => 'boolean',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 2,
                'question_key' => 'cook',
                'question' => 'Do you cook?',
                'answer_type' => 'boolean',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 2,
                'question_key' => 'assyrian_speak',
                'question' => 'Do you speak Assyrian in your household?',
                'answer_type' => 'boolean',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 2,
                'question_key' => 'social_media',
                'question' => 'What social media do you use?',
                'answer_type' => 'multi_select',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 2,
                'question_key' => 'assyrian_read_write',
                'question' => 'Do you read and write Assyrian?',
                'answer_type' => 'boolean',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 3,
                'question_key' => 'music',
                'question' => 'Do you play any music?',
                'answer_type' => 'boolean',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 3,
                'question_key' => 'assyrian_singer',
                'question' => 'Who is your favorite Assyrian singer?',
                'answer_type' => 'multi_select',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 3,
                'question_key' => 'assyrian_food',
                'question' => 'What is your favorite Assyrian food?',
                'answer_type' => 'multi_select',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 3,
                'question_key' => 'holidays',
                'question' => 'Do you celebrate all the holidays?',
                'answer_type' => 'boolean',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 3,
                'question_key' => 'heritage',
                'question' => 'Is preserving the Assyrian heritage important to you?',
                'answer_type' => 'boolean',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 3,
                'question_key' => 'family_speak',
                'question' => 'If you start a family, will you speak Assyrian in your household and with your kids?',
                'answer_type' => 'boolean',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 3,
                'question_key' => 'art',
                'question' => 'Do you like art?',
                'answer_type' => 'boolean',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 3,
                'question_key' => 'height',
                'question' => 'How tall are you?',
                'answer_type' => 'numeric',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 3,
                'question_key' => 'relocation',
                'question' => 'Are you willing to move for the love of your life to start a new life in a different city or country?',
                'answer_type' => 'boolean',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 3,
                'question_key' => 'live_with_parents',
                'question' => 'Do you live with your parents?',
                'answer_type' => 'boolean',
                'is_editable' => true,
                'is_required' => true,
            ],
            [
                'page' => 3,
                'question_key' => 'parents_alive',
                'question' => 'Are your parents still alive?',
                'answer_type' => 'boolean',
                'is_editable' => true,
                'is_required' => true,
            ],
        ];

        foreach ($questions as $data) {
            Question::create($data);
        }
    }
}
